import typescript from "@rollup/plugin-typescript";
import { nodeResolve } from "@rollup/plugin-node-resolve";

/**
 * Rollup config for Google Apps Script.
 *
 * Key constraints:
 * - Apps Script expects a flat set of .gs files with top-level functions.
 * - There is no module system on the server — output must be IIFE or plain script.
 * - Any NPM packages used must be inlined (no dynamic require/import at runtime).
 * - Functions that Apps Script needs to call (onOpen, triggers, custom functions)
 *   must be global — Rollup's IIFE wrapper will scope them unless we handle it.
 *
 * The "footer" trick below closes the IIFE early and re-exposes our entry-point
 * exports as global functions so Apps Script can find them.
 */
export default {
  input: "src/server/index.ts",
  output: {
    dir: "dist",
    format: "iife",
    // The IIFE is assigned to this variable; we don't actually use it,
    // but Rollup requires a name for IIFE format.
    name: "_GASEntry",
    // Prevent Rollup from code-splitting into multiple chunks.
    // Apps Script doesn't support ES module imports between files.
    inlineDynamicImports: true,
    sourcemap: true,
    // Expose the top-level exports as globals. The banner/footer below
    // unwrap them from the IIFE so Apps Script can call them directly.
    banner: "/* Apps Script Bundle — generated by Rollup. Do not edit. */",
    // This takes the exports from your entry point and makes them 
    // real top-level functions in the final .gs file.
    footer: `
/**
 * Global Handshake — Explicit function stubs for Google Apps Script discovery.
 *
 * Every export from index.ts that Apps Script needs to call must have a
 * matching one-line stub here. Rollup's IIFE wrapper scopes everything inside
 * _GASEntry; these stubs re-expose the relevant functions in the global scope.
 *
 * CUSTOM FUNCTIONS: If the stub is for a Sheets custom function (callable from
 * a cell formula), you MUST add a JSDoc comment with @customfunction directly
 * on the stub below. The TypeScript-level JSDoc is compiled away by Rollup and
 * does NOT appear on the global stub. Google Sheets only recognises a function
 * as a custom function when @customfunction is present on the global declaration
 * — without it the function will not appear in autocomplete or parameter hints.
 */
function onOpen(e) { _GASEntry.onOpen(e); }
function showSidebar() { _GASEntry.showSidebar(); }
function runTool(fn) { _GASEntry.runTool(fn); }
function showSourceDialog() { _GASEntry.showSourceDialog(); }
function handleDialogSelection(mode) { _GASEntry.handleDialogSelection(mode); }
function importDriveLinks() { _GASEntry.importDriveLinks(); }
function extractTextFromSelection() { _GASEntry.extractTextFromSelection(); }
function sampleRowsToEvaluation() { _GASEntry.sampleRowsToEvaluation(); }
/**
 * Call the Gemini API from a spreadsheet cell.
 * @param {string|Array} userTexts One or more text parts for the user message.
 *   Pass a single string, a cell reference, or a range / array literal.
 * @param {string} systemPrompt System-level instruction for the model.
 * @param {string|Array} toolNames Names of pre-registered tools to enable.
 * @return {string} The model's text response, or "[SSI Error: ...]" on failure.
 * @customfunction
 */
function SSI(userTexts, systemPrompt, toolNames) { return _GASEntry.SSI(userTexts, systemPrompt, toolNames); }
`,
  },
  plugins: [
    nodeResolve({
      // Only resolve modules that are actual NPM packages,
      // not Node.js built-ins (which don't exist in Apps Script).
      preferBuiltins: false,
    }),
    typescript({
      tsconfig: "./tsconfig.json",
    }),
  ],
};
